name: Checkers

on:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

jobs:

  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: JustinBeckwith/linkinator-action@v1.11.0
      with:
        linksToSkip: '^https://github.com/ ^https://www.jwz.org/ ^https://opensource.org/ ^https://unix.stackexchange.com/'
        paths: '*.md doc/*.md helpers/*.md'

  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: tbroadley/spellchecker-cli-action@v1
      with:
        dictionaries: '.github/dictionary.txt'
        files: '*.md doc/*.md helpers/*.md'
